package migrate

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
)

// rewriteConstructor adds the Orkestra constructor for receiverType.
//
// The existing reconciler struct and its client field are left untouched.
// The generated constructor adapts the existing controller-runtime reconciler
// to Orkestra:
//
//	func NewWebAppReconciler(kube kubeclient.Interface) domain.Reconciler {
//		return domain.ReconcilerFrom(&WebAppReconciler{
//			k8sClient: orkadapter.ToClient(kube),
//		})
//	}
//
// If the constructor already exists, src is returned unchanged.
func rewriteConstructor(src []byte, receiverType string) ([]byte, []string) {
	if receiverType == "" {
		return src, nil
	}

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "", src, parser.ParseComments)
	if err != nil {
		return src, []string{
			fmt.Sprintf(
				"could not parse source while generating constructor: %v",
				err,
			),
		}
	}

	constructorName := "New" + receiverType

	// Skip if a constructor with this name already exists.
	for _, decl := range f.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if ok && fn.Recv == nil && fn.Name.Name == constructorName {
			return src, nil
		}
	}

	fieldKey, found := clientFieldKey(f, receiverType)
	if !found {
		return src, []string{
			fmt.Sprintf(
				"could not locate a controller-runtime client.Client field on %s; constructor was not generated",
				receiverType,
			),
		}
	}

	constructor := fmt.Sprintf(`
	// %s is the Orkestra constructor. It replaces SetupWithManager — no other
	// changes to the reconciler are needed. ToClient returns the same client.Client
	// your reconciler already uses; ReconcilerFrom adapts the signature.
	// Generated by ork migrate
	func %s(kube kubeclient.Interface) domain.Reconciler {
		return domain.ReconcilerFrom(&%s{
			%s: orkadapter.ToClient(kube),
		})
	}
	`, constructorName, constructorName, receiverType, fieldKey)

	return append(src, []byte(constructor)...), nil
}

// prepareRewrite parses the source and extracts the reconciler metadata shared
// by all migration modes.
func prepareRewrite(src []byte, mode Mode) (*token.FileSet, *ast.File, *Result, *ast.FuncDecl, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "", src, parser.ParseComments)
	if err != nil {
		return nil, nil, nil, nil, fmt.Errorf("parse: %w", err)
	}

	res := &Result{
		PkgName: f.Name.Name,
		Mode:    mode,
	}

	fn := findReconcile(f)
	if fn == nil {
		return nil, nil, nil, nil, fmt.Errorf(
			"no Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) found",
		)
	}

	if len(fn.Recv.List) > 0 {
		res.ReceiverType = typeName(fn.Recv.List[0].Type)
	}

	res.Primary, res.Owns, res.Watches = extractOwnsWatches(f)

	return fset, f, res, fn, nil
}

// finishRewrite formats the rewritten source and stores it on the migration
// result, preserving the unformatted source when gofmt fails.
func finishRewrite(src []byte, res *Result) (*Result, error) {
	formatted, fmtErr := format.Source(src)
	if fmtErr != nil {
		res.Warnings = append(res.Warnings, fmt.Sprintf("gofmt failed (%v) — check output manually", fmtErr))
		res.Source = src
	} else {
		res.Source = formatted
	}

	return res, nil
}
