// Code generated by "ork generate registry" on 2026-09-07T13:17:20Z. DO NOT EDIT.
// Re-generate by running: ork generate registry --file <path-or-url>
package main

import (
	"context"

	"github.com/orkspace/orkestra/cmd/cli"
	"github.com/orkspace/orkestra/pkg/konfig"
	"github.com/orkspace/orkestra/pkg/logger"
	"github.com/orkspace/orkestra/pkg/utils"

	_ "github.com/orkspace/orkestra-ctrlruntime-constructor/pkg/typeregistry"
)

func main() {
	kfg, err := konfig.Init()
	if err != nil {
		logger.Fatal().AnErr("failed to load configurations", err)
		utils.Exit(err)
	}
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	cli.Execute(kfg, ctx)
}
